config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "tasks#index"

  get    "tasks",          to: "tasks#index"

  get    "tasks/new",      to: "tasks#new"
  post   "tasks",          to: "tasks#create"

  # NB: The `show` route needs to be *after* `new` route.
  get    "tasks/:id",      to: "tasks#show", as: "task"

  get    "tasks/:id/edit", to: "tasks#edit", as: "tasks_edit"
  patch  "tasks/:id",      to: "tasks#update"

  delete "tasks/:id",      to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  before_save :default_values
  def default_values
    self.completed ||= false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManagerTa</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h2>Editar a Tarefa </h2>
    <div class="row">
      <%= form_for(@task) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :details %>
          <%= f.text_field :details, class: 'form-control' %>
        </div>

        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>Hello Index Page</h1>
  <% @tasks.each do |task| %>
    <ul id="tasks">
      <li>
        <% if task.completed %>
          <i class="far fa-check-square"></i>
        <% else %>
          <i class="fa fa-square-o"></i>
        <% end %>
        <%= link_to "#{task.name}", task_path(task.id) %>
        <%= link_to task_path(task.id), method: :delete, data: { confirm: "Delete #{task.name}?" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
      </li>
    </ul>
  <% end %>
  <%= link_to "Adicionar Novo", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h2>Adicionar Nova Tarefa </h2>
    <div class="row">
      <%= form_for(@task) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :details %>
          <%= f.text_field :details, class: 'form-control' %>
        </div>

        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h2><%= @task.name %></h2>
  <p><%= @task.details %></p>
  <%= link_to "Editar", tasks_edit_path(@task) %>
  <%= link_to "Voltar para a Lista", tasks_path %>
</div>